const utils = require('./utils')

module.exports = function(bundler) {
  bundler.addAssetType('js', require.resolve('./RNWAsset'))
  bundler.addAssetType('jsx', require.resolve('./RNWAsset'))
  bundler.addAssetType('web.js', require.resolve('./RNWAsset'))
  bundler.addAssetType('web.jsx', require.resolve('./RNWAsset'))
  bundler.addAssetType(
    'web.ts',
    require.resolve(utils.getParcelPath() + 'lib/assets/TypeScriptAsset')
  )
  bundler.addAssetType(
    'web.tsx',
    require.resolve(utils.getParcelPath() + 'lib/assets/TypeScriptAsset')
  )
}

/* async function getBabelrc() {
  const conf = await config.resolve(cwd, ['.babelrc', '.babelrc.js'])
  if (conf) {
    return await config.load(cwd, ['.babelrc', '.babelrc.js'])
  }
}

let cwd = process.cwd()
const appPackage = require(cwd + '/package.json')
var Singleton = (function getAppBabelConfig() {
  if (appPackage && appPackage.babel) {
    console.log(appPackage.babel, 'yyyyyyyyyyyyyyy')
  } else {
    getBabelrc()
      .then(config => {
        console.log(config, 'ooooooooooooooo')
      })
      .catch(error => {
        console.log(error)
      })
  }
})() */

/* const that = {
  id: 1,
  name: 'C:\\Users\\Dalci\\Playground\\react-native-material-ui-web-app\\src\\index.js',
  basename: 'index.js',
  relativeName: 'index.js',
  package:
   { name: 'react-native-material-ui-web-app',
     version: '0.1.0',
     private: true,
     scripts:
      { start: 'parcel public/index.html',
        build: 'parcel build src/index.js --no-cache',
        test: 'react-scripts test --env=jsdom' },
     dependencies:
      { 'babel-plugin-react-native-web': '^0.5.1',
        'babel-preset-env': '^1.6.1',
        'babel-preset-react-native': '^4.0.0',
        react: '^16.2.0',
        'react-dom': '^16.2.0',
        'react-native-material-ui': '^1.19.0',
        'react-native-md-textinput': '^2.0.4',
        'react-native-vector-icons': '^4.5.0',
        'react-native-web': '^0.5.1',
        'react-router-dom': '^4.2.2',
        'react-sidebar': '^2.3.2' },
     'parcel-rnw': [ 'react-native-md-textinput', 'react-native-vector-icons' ],
     devDependencies:
      { 'babel-core': '^6.26.0',
        'parcel-plugin-react-native-web': '0.2.10',
        'babel-plugin-transform-flow-strip-types': '^6.22.0' },
     babel: { plugins: [Array] },
     pkgfile: 'C:\\Users\\Dalci\\Playground\\react-native-material-ui-web-app\\package.json' },
  options:
   { outDir: 'C:\\Users\\Dalci\\Playground\\react-native-material-ui-web-app\\dist',
     outFile: '',
     publicURL: '/dist',
     watch: false,
     cache: false,
     cacheDir: 'C:\\Users\\Dalci\\Playground\\react-native-material-ui-web-app\\.cache',
     killWorkers: true,
     minify: true,
     target: 'browser',
     hmr: false,
     https: false,
     logLevel: 3,
     mainFile: 'C:\\Users\\Dalci\\Playground\\react-native-material-ui-web-app\\src\\index.js',
     hmrPort: 0,
     rootDir: 'C:\\Users\\Dalci\\Playground\\react-native-material-ui-web-app\\src',
     sourceMaps: false,
     hmrHostname: '',
     detailedReport: false,
     extensions:
      { '.js': 'C:\\Users\\Dalci\\Playground\\parcel-plugin-react-native-web\\RNWAsset.js',
        '.jsx': 'C:\\Users\\Dalci\\Playground\\parcel-plugin-react-native-web\\RNWAsset.js',
        '.es6': './assets/JSAsset',
        '.jsm': './assets/JSAsset',
        '.mjs': './assets/JSAsset',
        '.ml': './assets/ReasonAsset',
        '.re': './assets/ReasonAsset',
        '.ts': './assets/TypeScriptAsset',
        '.tsx': './assets/TypeScriptAsset',
        '.coffee': './assets/CoffeeScriptAsset',
        '.json': './assets/JSONAsset',
        '.json5': './assets/JSONAsset',
        '.yaml': './assets/YAMLAsset',
        '.yml': './assets/YAMLAsset',
        '.toml': './assets/TOMLAsset',
        '.gql': './assets/GraphqlAsset',
        '.graphql': './assets/GraphqlAsset',
        '.css': './assets/CSSAsset',
        '.pcss': './assets/CSSAsset',
        '.styl': './assets/StylusAsset',
        '.less': './assets/LESSAsset',
        '.sass': './assets/SASSAsset',
        '.scss': './assets/SASSAsset',
        '.html': './assets/HTMLAsset',
        '.htm': './assets/HTMLAsset',
        '.rs': './assets/RustAsset',
        '.webmanifest': './assets/WebManifestAsset',
        '.web.js': 'C:\\Users\\Dalci\\Playground\\parcel-plugin-react-native-web\\RNWAsset.js',
        '.web.jsx': 'C:\\Users\\Dalci\\Playground\\parcel-plugin-react-native-web\\RNWAsset.js',
        '.web.ts': 'C:\\Users\\Dalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\parcel-bundler\\lib\\assets\\TypeScriptAsset.js',
        '.web.tsx': 'C:\\Users\\Dalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\parcel-bundler\\lib\\assets\\TypeScriptAsset.js' },
     bundleLoaders:
      { wasm: 'C:\\Users\\Dalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\parcel-bundler\\src\\builtins\\loaders\\wasm-loader.js',
        css: 'C:\\Users\\Dalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\parcel-bundler\\src\\builtins\\loaders\\css-loader.js',
        js: 'C:\\Users\\Dalci\\AppData\\Local\\Yarn\\config\\global\\node_modules\\parcel-bundler\\src\\builtins\\loaders\\js-loader.js' },
     env:
      { ALLUSERSPROFILE: 'C:\\ProgramData',
        APPDATA: 'C:\\Users\\Dalci\\AppData\\Roaming',
        CommonProgramFiles: 'C:\\Program Files\\Common Files',
        'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
        CommonProgramW6432: 'C:\\Program Files\\Common Files',
        COMPUTERNAME: 'DESKTOP-50RAUHC',
        ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe',
        FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
        FPS_BROWSER_USER_PROFILE_STRING: 'Default',
        HMR_HOSTNAME: undefined,
        HMR_PORT: '0',
        HOMEDRIVE: 'C:',
        HOMEPATH: '\\Users\\Dalci',
        LANG: 'en_US.UTF-8',
        LOCALAPPDATA: 'C:\\Users\\Dalci\\AppData\\Local',
        LOGONSERVER: '\\\\DESKTOP-50RAUHC',
        NODE: 'C:\\Program Files\\nodejs\\node.exe',
        NODE_ENV: 'production',
        npm_config_argv: '{"remain":[],"cooked":["run","build"],"original":["build"]}',
        npm_config_email: 'dalcib@gmail.com',
        npm_config_ignore_optional: undefined,
        npm_config_ignore_scripts: undefined,
        npm_config_init_author_email: 'dalci.b+npm@gmail.com',
        npm_config_init_author_name: 'Dalci de Jesus Bagolin',
        npm_config_init_author_url: 'https://github.org/dalcib',
        npm_config_init_license: 'MIT',
        npm_config_init_version: '1.0.0',
        npm_config_registry: 'https://registry.yarnpkg.com',
        npm_config_save_prefix: '^',
        npm_config_strict_ssl: 'true',
        npm_config_username: 'dalcib',
        npm_config_user_agent: 'yarn/1.3.2 npm/? node/v9.3.0 win32 x64',
        npm_config_version_git_message: 'v%s',
        npm_config_version_git_sign: undefined,
        npm_config_version_git_tag: 'true',
        npm_config_version_tag_prefix: 'v',
        npm_execpath: 'C:\\Users\\Dalci\\AppData\\Roaming\\npm\\node_modules\\yarn\\bin\\yarn.js',
        npm_lifecycle_event: 'build',
        npm_lifecycle_script: 'parcel build src/index.js --no-cache',
        npm_node_execpath: 'C:\\Program Files\\nodejs\\node.exe',
        npm_package_babel_plugins_0: 'transform-flow-strip-types',
        npm_package_dependencies_babel_plugin_react_native_web: '^0.5.1',
        npm_package_dependencies_babel_preset_env: '^1.6.1',
        npm_package_dependencies_babel_preset_react_native: '^4.0.0',
        npm_package_dependencies_react: '^16.2.0',
        npm_package_dependencies_react_dom: '^16.2.0',
        npm_package_dependencies_react_native_material_ui: '^1.19.0',
        npm_package_dependencies_react_native_md_textinput: '^2.0.4',
        npm_package_dependencies_react_native_vector_icons: '^4.5.0',
        npm_package_dependencies_react_native_web: '^0.5.1',
        npm_package_dependencies_react_router_dom: '^4.2.2',
        npm_package_dependencies_react_sidebar: '^2.3.2',
        npm_package_description: 'This app uses create-react-app with react-app-rewired to modify webpack',
        npm_package_devDependencies_babel_core: '^6.26.0',
        npm_package_devDependencies_babel_plugin_transform_flow_strip_types: '^6.22.0',
        npm_package_devDependencies_parcel_plugin_react_native_web: '0.2.10',
        npm_package_name: 'react-native-material-ui-web-app',
        npm_package_parcel_rnw_0: 'react-native-md-textinput',
        npm_package_parcel_rnw_1: 'react-native-vector-icons',
        npm_package_private: 'true',
        npm_package_readmeFilename: 'README.md',
        npm_package_scripts_build: 'parcel build src/index.js --no-cache',
        npm_package_scripts_start: 'parcel public/index.html',
        npm_package_scripts_test: 'react-scripts test --env=jsdom',
        npm_package_version: '0.1.0',
        NUMBER_OF_PROCESSORS: '4',
        OneDrive: 'C:\\Users\\Dalci\\OneDrive - MINISTERIO DA AGRICULTURA, PECUARIA E ABASTECIMENTO',
        OnlineServices: 'Online Services',
        OS: 'Windows_NT',
        Path: 'C:\\Users\\Dalci\\Playground\\react-native-material-ui-web-app\\node_modules\\.bin;C:\\Users\\Dalci\\AppData\\Local\\Yarn\\config\\link\\node_modules\\.bin;C:\\Users\\Dalci\\Playground\\react-native-material-ui-web-app\\node_modules\\.bin;C:\\Users\\Dalci\\AppData\\Local\\Yarn\\config\\link\\node_modules\\.bin;C:\\Program Files\\lib\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\HP\\IdrsOCR_15.2.10.1114\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files\\Aladdin\\eToken\\PKIClient\\x32;C:\\Program Files\\Aladdin\\eToken\\PKIClient\\x64;C:\\Users\\Dalci\\AppData\\Local\\Yarn\\bin;C:\\Users\\Dalci\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Dalci\\AppData\\Roaming\\npm;C:\\Program Files\\Microsoft VS Code\\bin;',
        PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC',
        platformcode: '7F',
        PROCESSOR_ARCHITECTURE: 'AMD64',
        PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 158 Stepping 9, GenuineIntel',
        PROCESSOR_LEVEL: '6',
        PROCESSOR_REVISION: '9e09',
        ProgramData: 'C:\\ProgramData',
        ProgramFiles: 'C:\\Program Files',
        'ProgramFiles(x86)': 'C:\\Program Files (x86)',
        ProgramW6432: 'C:\\Program Files',
        PROMPT: '$P$G',
        PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
        PUBLIC: 'C:\\Users\\Public',
        RegionCode: 'APJ',
        SESSIONNAME: 'Console',
        SystemDrive: 'C:',
        SystemRoot: 'C:\\WINDOWS',
        TEMP: 'C:\\Users\\Dalci\\AppData\\Local\\Temp',
        TERM_PROGRAM: 'vscode',
        TERM_PROGRAM_VERSION: '1.20.1',
        TMP: 'C:\\Users\\Dalci\\AppData\\Local\\Temp',
        USERDOMAIN: 'DESKTOP-50RAUHC',
        USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-50RAUHC',
        USERNAME: 'Dalci',
        USERPROFILE: 'C:\\Users\\Dalci',
        VSCODE_CWD: 'C:\\Users\\Dalci\\Playground',
        VSCODE_IPC_HOOK: '\\\\.\\pipe\\8c6d4344d460aff286e04c5b5c53497a-1.20.1-main-sock',
        VSCODE_NLS_CONFIG: '{"locale":"en-us","availableLanguages":{}}',
        VSCODE_NODE_CACHED_DATA_DIR_7364: 'C:\\Users\\Dalci\\AppData\\Roaming\\Code\\CachedData\\f88bbf9137d24d36d968ea6b2911786bfe103002',
        VSCODE_PID: '7364',
        windir: 'C:\\WINDOWS',
        YARN_WRAP_OUTPUT: 'false' },
     parser:  { extensions: [Object] } },
  encoding: 'utf8',
  type: 'js',
  processed: false,
  contents: null,
  ast: null,
  generated: null,
  hash: null,
  parentDeps:  {},
  dependencies:  {},
  depAssets:  {},
  parentBundle: null,
  bundles:  {},
  cacheData: { env: {} },
  buildTime: 0,
  bundledSize: 0,
  globals:  {},
  isAstDirty: false,
  isES6Module: false
} */
